
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1307:The behavior of 'string.Equals(string)' could vary based on the current user's locale settings. Replace this call in 'RealEstate.Services.Base.BaseService.UpdateAsync<TSource>(TSource, System.Action<RealEstate.Services.ViewModels.CurrentUserViewModel>, RealEstate.Base.Enums.Role[], bool, RealEstate.Base.Enums.StatusEnum)' with a call to 'string.Equals(string, System.StringComparison)'.", Justification = "<Pending>", Scope = "member", Target = "~M:RealEstate.Services.Base.BaseService.UpdateAsync``1(``0,System.Action{RealEstate.Services.ViewModels.CurrentUserViewModel},RealEstate.Base.Enums.Role[],System.Boolean,RealEstate.Base.Enums.StatusEnum)~System.Threading.Tasks.Task{RealEstate.Base.MethodStatus{``0}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'int.Parse(string)' could vary based on the current user's locale settings. Replace this call in 'string.PersianToGregorian()' with a call to 'int.Parse(string, IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:RealEstate.Services.Extensions.DateConverterExtension.PersianToGregorian(System.String)~System.DateTime")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'int.Parse(string)' could vary based on the current user's locale settings. Replace this call in 'string.TranslateFeature(string)' with a call to 'int.Parse(string, IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:RealEstate.Services.Extensions.FeatureFixExtension.TranslateFeature(System.String,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'string.Format(string, params object[])' could vary based on the current user's locale settings. Replace this call in 'KavehNegarProvider.GetApiPath(string, string, string)' with a call to 'string.Format(IFormatProvider, string, params object[])'.", Justification = "<Pending>", Scope = "member", Target = "~M:RealEstate.Services.Extensions.KavenNegarProvider.KavehNegarProvider.GetApiPath(System.String,System.String,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'long.Parse(string)' could vary based on the current user's locale settings. Replace this call in 'DateHelper.DateTimeToUnixTimestamp(DateTime)' with a call to 'long.Parse(string, IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:RealEstate.Services.Extensions.KavenNegarProvider.Utils.DateHelper.DateTimeToUnixTimestamp(System.DateTime)~System.Int64")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1307:The behavior of 'string.StartsWith(string)' could vary based on the current user's locale settings. Replace this call in 'RealEstate.Services.Extensions.ModelStateExtensions.IsValid(Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary, string)' with a call to 'string.StartsWith(string, System.StringComparison)'.", Justification = "<Pending>", Scope = "member", Target = "~M:RealEstate.Services.Extensions.ModelStateExtensions.IsValid(Microsoft.AspNetCore.Mvc.ModelBinding.ModelStateDictionary,System.String)~System.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1307:The behavior of 'string.Replace(string, string)' could vary based on the current user's locale settings. Replace this call in 'RealEstate.Services.Extensions.NumberProcessorExtensions.CurrencyToWords(string)' with a call to 'string.Replace(string, string, System.StringComparison)'.", Justification = "<Pending>", Scope = "member", Target = "~M:RealEstate.Services.Extensions.NumberProcessorExtensions.CurrencyToWords(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'ulong.ToString()' could vary based on the current user's locale settings. Replace this call in 'string.CurrencyToWords()' with a call to 'ulong.ToString(IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:RealEstate.Services.Extensions.NumberProcessorExtensions.CurrencyToWords(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1307:The behavior of 'string.Equals(string)' could vary based on the current user's locale settings. Replace this call in 'RealEstate.Services.Extensions.TagHelpers.NavBarButtonTagHelper.ProcessAsync(Microsoft.AspNetCore.Razor.TagHelpers.TagHelperContext, Microsoft.AspNetCore.Razor.TagHelpers.TagHelperOutput)' with a call to 'string.Equals(string, System.StringComparison)'.", Justification = "<Pending>", Scope = "member", Target = "~M:RealEstate.Services.Extensions.TagHelpers.NavBarButtonTagHelper.ProcessAsync(Microsoft.AspNetCore.Razor.TagHelpers.TagHelperContext,Microsoft.AspNetCore.Razor.TagHelpers.TagHelperOutput)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'int.Parse(string)' could vary based on the current user's locale settings. Replace this call in 'EmployeeService.PresenceAddAsync(PresenceInputViewModel, bool)' with a call to 'int.Parse(string, IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:RealEstate.Services.ServiceLayer.EmployeeService.PresenceAddAsync(RealEstate.Services.ViewModels.Input.PresenceInputViewModel,System.Boolean)~System.Threading.Tasks.Task{RealEstate.Base.MethodStatus{RealEstate.Services.Database.Tables.Presence}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'int.Parse(string)' could vary based on the current user's locale settings. Replace this call in 'EmployeeService.PresenceUpdateAsync(PresenceInputViewModel, bool)' with a call to 'int.Parse(string, IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:RealEstate.Services.ServiceLayer.EmployeeService.PresenceUpdateAsync(RealEstate.Services.ViewModels.Input.PresenceInputViewModel,System.Boolean)~System.Threading.Tasks.Task{RealEstate.Base.MethodStatus{RealEstate.Services.Database.Tables.Presence}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'long.ToString()' could vary based on the current user's locale settings. Replace this call in 'SmsService.SendAsync(List<string>, string)' with a call to 'long.ToString(IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:RealEstate.Services.ServiceLayer.SmsService.SendAsync(System.Collections.Generic.List{System.String},System.String)~System.Threading.Tasks.Task{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1305:The behavior of 'long.ToString()' could vary based on the current user's locale settings. Replace this call in 'SmsService.SendAsync(string[], SmsTemplateEnum, params string[])' with a call to 'long.ToString(IFormatProvider)'.", Justification = "<Pending>", Scope = "member", Target = "~M:RealEstate.Services.ServiceLayer.SmsService.SendAsync(System.String[],RealEstate.Base.Enums.SmsTemplateEnum,System.String[])~System.Threading.Tasks.Task{System.}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1307:The behavior of 'string.Equals(string)' could vary based on the current user's locale settings. Replace this call in 'RealEstate.Services.BaseLog.BaseLogViewModel.Id.get' with a call to 'string.Equals(string, System.StringComparison)'.", Justification = "<Pending>", Scope = "member", Target = "~P:RealEstate.Services.BaseLog.BaseLogViewModel.Id")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1307:The behavior of 'string.Equals(string)' could vary based on the current user's locale settings. Replace this call in 'RealEstate.Services.BaseLog.BaseLogViewModel.Logs.get' with a call to 'string.Equals(string, System.StringComparison)'.", Justification = "<Pending>", Scope = "member", Target = "~P:RealEstate.Services.BaseLog.BaseLogViewModel.Logs")]