//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealEstate.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائید.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعالسازی.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت این امکان.
        /// </summary>
        public static string AddThisFacility {
            get {
                return ResourceManager.GetString("AddThisFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت این مشخصه.
        /// </summary>
        public static string AddThisFeature {
            get {
                return ResourceManager.GetString("AddThisFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت این اپراتور.
        /// </summary>
        public static string AddThisOperator {
            get {
                return ResourceManager.GetString("AddThisOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیر.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساعده.
        /// </summary>
        public static string Advance {
            get {
                return ResourceManager.GetString("Advance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوچه.
        /// </summary>
        public static string Alley {
            get {
                return ResourceManager.GetString("Alley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string AlreadyDeleted {
            get {
                return ResourceManager.GetString("AlreadyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این مورد از قبل موجود است..
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این کاربر پیش از شما وارد سامانه شده است.
        /// </summary>
        public static string AlreadySignedIn {
            get {
                return ResourceManager.GetString("AlreadySignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متقاضی.
        /// </summary>
        public static string Applicant {
            get {
                return ResourceManager.GetString("Applicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتظارات متقاضی.
        /// </summary>
        public static string ApplicantFeatures {
            get {
                return ResourceManager.GetString("ApplicantFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متقاضیان.
        /// </summary>
        public static string Applicants {
            get {
                return ResourceManager.GetString("Applicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاورین املاک موسی زاده.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoosaZadeh RealEstates Agency.
        /// </summary>
        public static string AppNameEng {
            get {
                return ResourceManager.GetString("AppNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا اطمینان به انجام این درخواست دارید؟.
        /// </summary>
        public static string AreYouSureToDoThisRequest {
            get {
                return ResourceManager.GetString("AreYouSureToDoThisRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذینفع.
        /// </summary>
        public static string Beneficiary {
            get {
                return ResourceManager.GetString("Beneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام ساختمان.
        /// </summary>
        public static string BuildingName {
            get {
                return ResourceManager.GetString("BuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پلاک.
        /// </summary>
        public static string BuildingNumber {
            get {
                return ResourceManager.GetString("BuildingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرید.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توسط.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندیها.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش از تکمیل این فرم، در صورت نیاز به ایجاد تغییرات، روی دکمه زیر کلید/تپ کنید.
        /// </summary>
        public static string ChangeDealBeforeAccept {
            get {
                return ResourceManager.GetString("ChangeDealBeforeAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چک ها.
        /// </summary>
        public static string Checks {
            get {
                return ResourceManager.GetString("Checks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد کمیسیون.
        /// </summary>
        public static string CommissionPercent {
            get {
                return ResourceManager.GetString("CommissionPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ کمیسیون.
        /// </summary>
        public static string CommissionPrice {
            get {
                return ResourceManager.GetString("CommissionPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکمیل شده.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تحویل.
        /// </summary>
        public static string ConstructionCompleteDateTime {
            get {
                return ResourceManager.GetString("ConstructionCompleteDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشارکت در ساخت.
        /// </summary>
        public static string ConstructionParticipatory {
            get {
                return ResourceManager.GetString("ConstructionParticipatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال ساخت.
        /// </summary>
        public static string ConstructionYear {
            get {
                return ResourceManager.GetString("ConstructionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سازنده.
        /// </summary>
        public static string Constructor {
            get {
                return ResourceManager.GetString("Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افراد.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت در سامانه.
        /// </summary>
        public static string CreatedDateTime {
            get {
                return ResourceManager.GetString("CreatedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری فعلی قابل شناسایی نیست..
        /// </summary>
        public static string CurrentUserIsUnreachable {
            get {
                return ResourceManager.GetString("CurrentUserIsUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتریان.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرفعالسازی.
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این حساب کاربری غیرفعال شده است.
        /// </summary>
        public static string Deactivated {
            get {
                return ResourceManager.GetString("Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قرارداد.
        /// </summary>
        public static string Deal {
            get {
                return ResourceManager.GetString("Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی قرارداد.
        /// </summary>
        public static string DealCategory {
            get {
                return ResourceManager.GetString("DealCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتمام معامله.
        /// </summary>
        public static string DealFinish {
            get {
                return ResourceManager.GetString("DealFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرف اول قراداد.
        /// </summary>
        public static string DealFirstPerson {
            get {
                return ResourceManager.GetString("DealFirstPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قراردادها.
        /// </summary>
        public static string Deals {
            get {
                return ResourceManager.GetString("Deals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرف دوم قرارداد.
        /// </summary>
        public static string DealSecondPerson {
            get {
                return ResourceManager.GetString("DealSecondPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت قراردادها.
        /// </summary>
        public static string DealsManagement {
            get {
                return ResourceManager.GetString("DealsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت معامله.
        /// </summary>
        public static string DealStatus {
            get {
                return ResourceManager.GetString("DealStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم نمایش.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش پرداخت.
        /// </summary>
        public static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ پیش پرداخت.
        /// </summary>
        public static string DepositPrice {
            get {
                return ResourceManager.GetString("DepositPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقه.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مناطق.
        /// </summary>
        public static string Districts {
            get {
                return ResourceManager.GetString("Districts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقسیم بندی ها.
        /// </summary>
        public static string Divisions {
            get {
                return ResourceManager.GetString("Divisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانگ.
        /// </summary>
        public static string Dong {
            get {
                return ResourceManager.GetString("Dong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش متقاضی.
        /// </summary>
        public static string EditApplicant {
            get {
                return ResourceManager.GetString("EditApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش دسته بندی.
        /// </summary>
        public static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش فرد.
        /// </summary>
        public static string EditContact {
            get {
                return ResourceManager.GetString("EditContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مشتری.
        /// </summary>
        public static string EditCustomer {
            get {
                return ResourceManager.GetString("EditCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش قرارداد.
        /// </summary>
        public static string EditDeal {
            get {
                return ResourceManager.GetString("EditDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش منطقه.
        /// </summary>
        public static string EditDistrict {
            get {
                return ResourceManager.GetString("EditDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش کارمند.
        /// </summary>
        public static string EditEmployee {
            get {
                return ResourceManager.GetString("EditEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش امکان.
        /// </summary>
        public static string EditFacility {
            get {
                return ResourceManager.GetString("EditFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مشخصه.
        /// </summary>
        public static string EditFeature {
            get {
                return ResourceManager.GetString("EditFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مورد.
        /// </summary>
        public static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مرخصی.
        /// </summary>
        public static string EditLeave {
            get {
                return ResourceManager.GetString("EditLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش درصد مدیریت.
        /// </summary>
        public static string EditManagementPercent {
            get {
                return ResourceManager.GetString("EditManagementPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش حضور و غیاب.
        /// </summary>
        public static string EditPresence {
            get {
                return ResourceManager.GetString("EditPresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش ملک.
        /// </summary>
        public static string EditProperty {
            get {
                return ResourceManager.GetString("EditProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش یادآوری.
        /// </summary>
        public static string EditReminder {
            get {
                return ResourceManager.GetString("EditReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش کاربر.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمند.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمندان.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایان کار.
        /// </summary>
        public static string EndOfWork {
            get {
                return ResourceManager.GetString("EndOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکانات.
        /// </summary>
        public static string Facilities {
            get {
                return ResourceManager.GetString("Facilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در انجام درخواست.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مشخصه.
        /// </summary>
        public static string FeatureType {
            get {
                return ResourceManager.GetString("FeatureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} را پر کنید..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} را آپلود کنید..
        /// </summary>
        public static string FileRequired {
            get {
                return ResourceManager.GetString("FileRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت نهایی.
        /// </summary>
        public static string FinalPrice {
            get {
                return ResourceManager.GetString("FinalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالی.
        /// </summary>
        public static string Financial {
            get {
                return ResourceManager.GetString("Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقوق ثابت.
        /// </summary>
        public static string FixedSalary {
            get {
                return ResourceManager.GetString("FixedSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آپارتمان.
        /// </summary>
        public static string Flat {
            get {
                return ResourceManager.GetString("Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد.
        /// </summary>
        public static string FlatNumber {
            get {
                return ResourceManager.GetString("FlatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طبقه.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه دسترسی به این درخواست را ندارید.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این مورد پیش از این به سامانه افزوده گردیده، اما شما اجازه بروز رسانی یا بازنمایش آن را ندارید..
        /// </summary>
        public static string ForbiddenAndUnableToUpdateOrShow {
            get {
                return ResourceManager.GetString("ForbiddenAndUnableToUpdateOrShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جریمه.
        /// </summary>
        public static string Forfeit {
            get {
                return ResourceManager.GetString("Forfeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از تاریخ.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از ساعت.
        /// </summary>
        public static string FromHour {
            get {
                return ResourceManager.GetString("FromHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هدیه.
        /// </summary>
        public static string Gift {
            get {
                return ResourceManager.GetString("Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمین.
        /// </summary>
        public static string Ground {
            get {
                return ResourceManager.GetString("Ground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه اصلی.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورتی که قبلا فرد مورد نظر را به سامانه اضافه کرده اید، انتخاب کنید:.
        /// </summary>
        public static string IfYouAlreadyCreatePerson {
            get {
                return ResourceManager.GetString("IfYouAlreadyCreatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورتی که قبلا ملک مورد نظر را به سامانه اضافه کرده اید، انتخاب کنید:.
        /// </summary>
        public static string IfYouAlreadyCreateProperty {
            get {
                return ResourceManager.GetString("IfYouAlreadyCreateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورتی که مایلید فرد جدید به سامانه اضافه کنید:.
        /// </summary>
        public static string IfYouWantToCreatePerson {
            get {
                return ResourceManager.GetString("IfYouWantToCreatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورتی که مایلید ملک جدید به سامانه اضافه کنید:.
        /// </summary>
        public static string IfYouWantToCreateProperty {
            get {
                return ResourceManager.GetString("IfYouWantToCreateProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیمه.
        /// </summary>
        public static string Insurance {
            get {
                return ResourceManager.GetString("Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مورد.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات مورد.
        /// </summary>
        public static string ItemFeatures {
            get {
                return ResourceManager.GetString("ItemFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست معامله.
        /// </summary>
        public static string ItemRequest {
            get {
                return ResourceManager.GetString("ItemRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست های معامله.
        /// </summary>
        public static string ItemRequests {
            get {
                return ResourceManager.GetString("ItemRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موارد.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول جغرافیایی.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرخصی ها.
        /// </summary>
        public static string Leaves {
            get {
                return ResourceManager.GetString("Leaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ وام.
        /// </summary>
        public static string LoanPrice {
            get {
                return ResourceManager.GetString("LoanPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به حساب کاربری.
        /// </summary>
        public static string LoginToAccount {
            get {
                return ResourceManager.GetString("LoginToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج از حساب کاربری.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض جغرافیایی.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصدهای مدیریت.
        /// </summary>
        public static string ManagementPercents {
            get {
                return ResourceManager.GetString("ManagementPercents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحت.
        /// </summary>
        public static string Measurement {
            get {
                return ResourceManager.GetString("Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واسطه.
        /// </summary>
        public static string Mediator {
            get {
                return ResourceManager.GetString("Mediator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدل پیدا نشد..
        /// </summary>
        public static string ModelNotFound {
            get {
                return ResourceManager.GetString("ModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت قرارداد (ماه).
        /// </summary>
        public static string MonthLength {
            get {
                return ResourceManager.GetString("MonthLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متقاضی جدید.
        /// </summary>
        public static string NewApplicant {
            get {
                return ResourceManager.GetString("NewApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی جدید.
        /// </summary>
        public static string NewCategory {
            get {
                return ResourceManager.GetString("NewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرد جدید.
        /// </summary>
        public static string NewContact {
            get {
                return ResourceManager.GetString("NewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری جدید.
        /// </summary>
        public static string NewCustomer {
            get {
                return ResourceManager.GetString("NewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قرارداد جدید.
        /// </summary>
        public static string NewDeal {
            get {
                return ResourceManager.GetString("NewDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقه جدید.
        /// </summary>
        public static string NewDistrict {
            get {
                return ResourceManager.GetString("NewDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمند جدید.
        /// </summary>
        public static string NewEmployee {
            get {
                return ResourceManager.GetString("NewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان جدید.
        /// </summary>
        public static string NewFacility {
            get {
                return ResourceManager.GetString("NewFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصه جدید.
        /// </summary>
        public static string NewFeature {
            get {
                return ResourceManager.GetString("NewFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مورد جدید.
        /// </summary>
        public static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرخصی جدید.
        /// </summary>
        public static string NewLeave {
            get {
                return ResourceManager.GetString("NewLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد مدیریت جدید.
        /// </summary>
        public static string NewManagementPercent {
            get {
                return ResourceManager.GetString("NewManagementPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالک جدید.
        /// </summary>
        public static string NewOwner {
            get {
                return ResourceManager.GetString("NewOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت جدید.
        /// </summary>
        public static string NewPayment {
            get {
                return ResourceManager.GetString("NewPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حضور و غیاب جدید.
        /// </summary>
        public static string NewPresence {
            get {
                return ResourceManager.GetString("NewPresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملک جدید.
        /// </summary>
        public static string NewProperty {
            get {
                return ResourceManager.GetString("NewProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یادآوری جدید.
        /// </summary>
        public static string NewReminder {
            get {
                return ResourceManager.GetString("NewReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرف دوم معامله جدید.
        /// </summary>
        public static string NewSecondPerson {
            get {
                return ResourceManager.GetString("NewSecondPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر جدید.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موردی برای نمایش وجود ندارد..
        /// </summary>
        public static string NoItemToShow {
            get {
                return ResourceManager.GetString("NoItemToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعلانات.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامتر خالی است.
        /// </summary>
        public static string NullParam {
            get {
                return ResourceManager.GetString("NullParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اپراتورها.
        /// </summary>
        public static string Operators {
            get {
                return ResourceManager.GetString("Operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالک.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالک انتخاب نشده است..
        /// </summary>
        public static string OwnerNotSelected {
            get {
                return ResourceManager.GetString("OwnerNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالکین.
        /// </summary>
        public static string Owners {
            get {
                return ResourceManager.GetString("Owners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مثلا: نام فرد، شماره موبایل فرد یا ....
        /// </summary>
        public static string OwnerSelectorPlaceholder {
            get {
                return ResourceManager.GetString("OwnerSelectorPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالکیت.
        /// </summary>
        public static string Ownership {
            get {
                return ResourceManager.GetString("Ownership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت کامل انجام نشد..
        /// </summary>
        public static string PartialSuccess {
            get {
                return ResourceManager.GetString("PartialSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت ها.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار درخواست.
        /// </summary>
        public static string PendingRequest {
            get {
                return ResourceManager.GetString("PendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار پاسخ.
        /// </summary>
        public static string PendingResponse {
            get {
                return ResourceManager.GetString("PendingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصاویر.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رهن.
        /// </summary>
        public static string Pledge {
            get {
                return ResourceManager.GetString("Pledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش فروش.
        /// </summary>
        public static string Presale {
            get {
                return ResourceManager.GetString("Presale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حضور و غیاب.
        /// </summary>
        public static string Presence {
            get {
                return ResourceManager.GetString("Presence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حضور و غیاب ها.
        /// </summary>
        public static string Presences {
            get {
                return ResourceManager.GetString("Presences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت هر متر.
        /// </summary>
        public static string PricePerMeter {
            get {
                return ResourceManager.GetString("PricePerMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to املاک.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملک.
        /// </summary>
        public static string Property {
            get {
                return ResourceManager.GetString("Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی ملک.
        /// </summary>
        public static string PropertyCategory {
            get {
                return ResourceManager.GetString("PropertyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات ملک.
        /// </summary>
        public static string PropertyDetail {
            get {
                return ResourceManager.GetString("PropertyDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکانات ملک.
        /// </summary>
        public static string PropertyFacilities {
            get {
                return ResourceManager.GetString("PropertyFacilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات ملک.
        /// </summary>
        public static string PropertyFeatures {
            get {
                return ResourceManager.GetString("PropertyFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملک انتخاب نشده است..
        /// </summary>
        public static string PropertyNotSelected {
            get {
                return ResourceManager.GetString("PropertyNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مثلا: نام مالک، آدرس مالک، آدرس ملک، منطقه و ....
        /// </summary>
        public static string PropertySelectorPlaceholder {
            get {
                return ResourceManager.GetString("PropertySelectorPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید بین {1} و {2} باشد..
        /// </summary>
        public static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دلیل.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رد شده.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مانده حساب.
        /// </summary>
        public static string Remain {
            get {
                return ResourceManager.GetString("Remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یادآوری.
        /// </summary>
        public static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یادآوری ها.
        /// </summary>
        public static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجاره.
        /// </summary>
        public static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ اجاره.
        /// </summary>
        public static string RentPrice {
            get {
                return ResourceManager.GetString("RentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب مجدد.
        /// </summary>
        public static string ResetSelection {
            get {
                return ResourceManager.GetString("ResetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .پس از بررسی دوباره امتحان کنید.
        /// </summary>
        public static string RetryAfterReview {
            get {
                return ResourceManager.GetString("RetryAfterReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطح دسترسی.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقوق.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروش.
        /// </summary>
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرف اول و دوم یکی هستند.
        /// </summary>
        public static string SameAsOwner {
            get {
                return ResourceManager.GetString("SameAsOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی افراد.
        /// </summary>
        public static string SearchPerson {
            get {
                return ResourceManager.GetString("SearchPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرف دوم.
        /// </summary>
        public static string SecondPerson {
            get {
                return ResourceManager.GetString("SecondPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب مالک.
        /// </summary>
        public static string SelectOwner {
            get {
                return ResourceManager.GetString("SelectOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب فرد.
        /// </summary>
        public static string SelectPerson {
            get {
                return ResourceManager.GetString("SelectPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب ملک.
        /// </summary>
        public static string SelectProperty {
            get {
                return ResourceManager.GetString("SelectProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب طرف دوم معامله.
        /// </summary>
        public static string SelectSecondPerson {
            get {
                return ResourceManager.GetString("SelectSecondPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامک ها.
        /// </summary>
        public static string Smses {
            get {
                return ResourceManager.GetString("Smses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات.
        /// </summary>
        public static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آغاز به کار.
        /// </summary>
        public static string StartWork {
            get {
                return ResourceManager.GetString("StartWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال افزودن مورد.
        /// </summary>
        public static string StateAddingDeal {
            get {
                return ResourceManager.GetString("StateAddingDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال افزودن منطقه.
        /// </summary>
        public static string StateAddingDistrict {
            get {
                return ResourceManager.GetString("StateAddingDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال افزودن امکان ملک.
        /// </summary>
        public static string StateAddingFacility {
            get {
                return ResourceManager.GetString("StateAddingFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال افزودن مشخصه ملک.
        /// </summary>
        public static string StateAddingFeature {
            get {
                return ResourceManager.GetString("StateAddingFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال افزودن فرد.
        /// </summary>
        public static string StateAddingPerson {
            get {
                return ResourceManager.GetString("StateAddingPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال افزودن ملک.
        /// </summary>
        public static string StateAddingProperty {
            get {
                return ResourceManager.GetString("StateAddingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال افزودن مشخصه مورد.
        /// </summary>
        public static string StateAddingSpecification {
            get {
                return ResourceManager.GetString("StateAddingSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال افزودن کاربر.
        /// </summary>
        public static string StateAddingUser {
            get {
                return ResourceManager.GetString("StateAddingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متصل به سامانه.
        /// </summary>
        public static string StateConnected {
            get {
                return ResourceManager.GetString("StateConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال ویرایش مورد.
        /// </summary>
        public static string StateEditingDeal {
            get {
                return ResourceManager.GetString("StateEditingDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال ویرایش منطقه.
        /// </summary>
        public static string StateEditingDistrict {
            get {
                return ResourceManager.GetString("StateEditingDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال ویرایش امکان ملک.
        /// </summary>
        public static string StateEditingFacility {
            get {
                return ResourceManager.GetString("StateEditingFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال ویرایش مشخصه ملک.
        /// </summary>
        public static string StateEditingFeature {
            get {
                return ResourceManager.GetString("StateEditingFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال ویرایش فرد.
        /// </summary>
        public static string StateEditingPerson {
            get {
                return ResourceManager.GetString("StateEditingPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال ویرایش ملک.
        /// </summary>
        public static string StateEditingProperty {
            get {
                return ResourceManager.GetString("StateEditingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال ویرایش مشخصه مورد.
        /// </summary>
        public static string StateEditingSpecification {
            get {
                return ResourceManager.GetString("StateEditingSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال ویرایش کاربر.
        /// </summary>
        public static string StateEditingUser {
            get {
                return ResourceManager.GetString("StateEditingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال مشاهده صفحه موارد.
        /// </summary>
        public static string StateWatchingDeals {
            get {
                return ResourceManager.GetString("StateWatchingDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال مشاهده صفحه تعیین وضعیت موارد.
        /// </summary>
        public static string StateWatchingDealStatuses {
            get {
                return ResourceManager.GetString("StateWatchingDealStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال مشاهده صفحه مناطق.
        /// </summary>
        public static string StateWatchingDistricts {
            get {
                return ResourceManager.GetString("StateWatchingDistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال مشاهده صفحه امکانات املاک.
        /// </summary>
        public static string StateWatchingFacilities {
            get {
                return ResourceManager.GetString("StateWatchingFacilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال مشاهده صفحه مشخصات املاک.
        /// </summary>
        public static string StateWatchingFeatures {
            get {
                return ResourceManager.GetString("StateWatchingFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال مشاهده صفحه افراد.
        /// </summary>
        public static string StateWatchingPersons {
            get {
                return ResourceManager.GetString("StateWatchingPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال مشاهده صفحه املاک.
        /// </summary>
        public static string StateWatchingProperties {
            get {
                return ResourceManager.GetString("StateWatchingProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال مشاهده صفحه آمار.
        /// </summary>
        public static string StateWatchingStatistics {
            get {
                return ResourceManager.GetString("StateWatchingStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال مشاهده صفحه کاربران.
        /// </summary>
        public static string StateWatchingUsers {
            get {
                return ResourceManager.GetString("StateWatchingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آمار.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایست!.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مغازه.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیابان.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیربنا.
        /// </summary>
        public static string Substructure {
            get {
                return ResourceManager.GetString("Substructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت انجام شد..
        /// </summary>
        public static string SuccessfullyDone {
            get {
                return ResourceManager.GetString("SuccessfullyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیر اصلی.
        /// </summary>
        public static string SuperAdmin {
            get {
                return ResourceManager.GetString("SuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد شیرینی.
        /// </summary>
        public static string TipPercent {
            get {
                return ResourceManager.GetString("TipPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ شیرینی.
        /// </summary>
        public static string TipPrice {
            get {
                return ResourceManager.GetString("TipPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا تاریخ.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا ساعت.
        /// </summary>
        public static string ToHour {
            get {
                return ResourceManager.GetString("ToHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره در بانک داده انجام نشد..
        /// </summary>
        public static string UnableToSave {
            get {
                return ResourceManager.GetString("UnableToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش.
        /// </summary>
        public static string Undelete {
            get {
                return ResourceManager.GetString("Undelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامشخص.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شده.
        /// </summary>
        public static string UpdatedDealStatus {
            get {
                return ResourceManager.GetString("UpdatedDealStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین وضعیت.
        /// </summary>
        public static string UpdateDealStatus {
            get {
                return ResourceManager.GetString("UpdateDealStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آپلود تصویر.
        /// </summary>
        public static string UploadPhotos {
            get {
                return ResourceManager.GetString("UploadPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی های مورد مجاز برای کاربر.
        /// </summary>
        public static string UserItemCategories {
            get {
                return ResourceManager.GetString("UserItemCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربری.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر پیدا نشد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی های ملک مجاز برای کاربر.
        /// </summary>
        public static string UserPropertyCategories {
            get {
                return ResourceManager.GetString("UserPropertyCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت فعلی کاربر.
        /// </summary>
        public static string UserState {
            get {
                return ResourceManager.GetString("UserState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده همه اعلانات.
        /// </summary>
        public static string ViewAllNotifications {
            get {
                return ResourceManager.GetString("ViewAllNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویلایی.
        /// </summary>
        public static string Villa {
            get {
                return ResourceManager.GetString("Villa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور اشتباه است.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
